config/routes.rb
Rails.application.routes.draw do
  resources :images
  get 'sessions/new'
  root             'public_pages#home'
  get 'help'    => 'public_pages#help'
  get 'about'   => 'public_pages#about'
  get 'contact' => 'public_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'blogs/create'

  resources :users
  resources :blogs, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "users#index"
end

app/models/blog.rb
class Blog
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Timestamps::Created
  include Mongoid::Paperclip

  embeds_many :images, cascade_callbacks: true
  accepts_nested_attributes_for :images
  validates :user_id, presence: true
  validates :content, length: { maximum: 1400 }, presence: true
  validate :image_size
  field :title, type: String
  field :content, type: String

  default_scope -> { order(created_at: :desc) }

  belongs_to :user

  private

  # Validates the size of an uploaded image.
  def image_size
    return if images.nil?
    if images.size > 5.megabytes
      errors.add(:image, "should be less than 5MB")
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy


  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1 or /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      flash[:success] = "blog created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy
    flash[:success] = "blog deleted"
    redirect_to request.referrer || root_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def correct_user
      @blog = current_user.blogs.find_by(id: params[:id])
      redirect_to root_url if @blog.nil?
    end

    def blog_params
      params.require(:blog).permit(:title, :content, images_attributes: [:images])
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<li id="blog-<%= blog.id %>">
  <%= link_to gravatar_for(blog.user, size: 50), blog.user %>
  <span class="user"><%= link_to blog.user.name, blog.user %></span>
  <span class="content">
    <%= blog.title %>
    <%= blog.content %>
    <%#= image_tag({blog.images.each do |img| img.photo.url end} if blog.images?) %>
    <% if blog.images.any? %>
      <div class="image-container">
        <% blog.images.each do |img| %>
          <%= image_tag image.url %>
        <% end %>
      </div>
    <% end %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(blog.created_at) %> ago.
    <% if current_user?(blog.user) %>
      <%= link_to "delete", blog, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/blogs/_form.html.erb
<%= form_for(blog, url: 'blogs_path') do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <!-- <div>
    <%#= form.label :user_id, style: "display: block" %>
    <%#= form.number_field :user_id %>
  </div> -->

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Show this blog", @blog %> |
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Blogs</h1>

<div id="blogs">
  <% @blogs.each do |blog| %>
    <%= render blog %>
    <p>
      <%= link_to "Show this blog", blog %>
    </p>
  <% end %>
</div>

<%= link_to "New blog", new_blog_path %>

app/views/blogs/new.html.erb
<h1>New blog</h1>

<%= render "form", blog: @blog %>

<br>

<div>
  <%= link_to "Back to blogs", blogs_path %>
</div>

app/views/blogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog %>

<div>
  <%= link_to "Edit this blog", edit_blog_path(@blog) %> |
  <%= link_to "Back to blogs", blogs_path %>

  <%= button_to "Destroy this blog", @blog, method: :delete %>
</div>