config/routes.rb
Rails.application.routes.draw do
  resources :images
  get 'sessions/new'
  root             'public_pages#home'
  get 'help'    => 'public_pages#help'
  get 'about'   => 'public_pages#about'
  get 'contact' => 'public_pages#contact'
  get 'signup'  => 'users#new'
  get 'login'   => 'sessions#new'
  post 'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  post 'blogs/create'

  resources :users
  resources :blogs, only: [:create, :destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "users#index"
end

app/views/shared/_blog_form.html.erb
<%= form_for(Blog.new, html: { multipart: true }, method: 'POST', url: blogs_path) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_field :title, placeholder: "Add title here..." %>
  </div>

  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new blog..." %>
  </div>
  <span class="image">
    <%#= f.fields_for :images do |image| %>
      <%# if image.object.new_record? %>
        <%= f.file_field :images, :multiple => true, accept: 'image/jpeg,image/gif,image/png' %>
      <%# end %>
    <%# end %>
  </span>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $('input[type="file"]').bind('change', function() {
    var size_in_megabytes = this.files[0].size / 1024 / 1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="blogs">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>


<!-- <%# if @feed_items.any? %>
  <ol class="blogs">
    <%# @feed_items.each do |feed_item| %>
      <li>
        <h3><%#= feed_item.title %></h3>
        <p> <%#= feed_item.content %> </p>
        <%# if feed_item.images.any? %>
          <div class="image-container">
            <%# feed_item.images.each do |image| %>
              <%#= image_tag(url_for(image.photo)) %>
            <%# end %>
          </div>
        <%# end %>
        <p><%#= feed_item.content %></p> -->
      <!-- </li> -->
    <%# end %>
  <!-- </ol> -->
  <%#= will_paginate @feed_items %>
<%# end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.blogs.count, "blog") %></span>